### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by chamini2** [angler-lang/angler-doc#1]
### TODO
- [x] Modo de pruebas
- [x] REPL
- [x] Pros & Cons de comportamientos
### Capítulo de Desarrollo
- [x] ¿Chequeo de tipos?
  - [ ] `open` es equivalente a `closed` una vez que se leyó el todo el código.
- [x] Pattern matching
- Capaz es desordenado así?
- INVESTIGACIÓN
### Feedback de GaCeLa
- [x] Hacer un estudio completo del estado del arte
- [ ] Cuidado con términos a utilizar
  
  > Por ejemplo: un estado con `(x < 0 and y > 3)` es ~~_válido_~~
  > 
  > > _válido_ no se debe usar, pues en lógica significa que es teorema
### Capítulo de Resultados
- [x] Diseño completo
  - Capaz tener algunas cosas para ejemplos definidas?
- [x] ¿Estado actual del interpretador?, por qué no importa que no se logró el chequeo de tipos
- [x] Comparaciones a otros lenguajes (expresividad, claridad, etc.)
- [ ] ¿Tiempos de parser de operadores mixfijos?
### Conclusiones / trabajo futuro
- [x] totality check
## Cambios de diseño a considerar
- [x] Agregar `undefined` / `error` y sus repercusiones
# Cosas a estar pendiente
- Comas, puntos y demás en los bloques matemáticos.
- Continuación de texto después de un bloque matemático (mayúscula, minúscula, etc.).
- Tiempos (pasado, presente) y sujeto (personal, impersonal) del discurso.
- Argumentos / Parámetros
- Definición / Declaración
- Parentizar referencias.
- Arreglar figuras / ecuaciones / captionof
## Cambio de palabras
- `[asume := supone]`
- `[note := nótese]`
- `[implantación := implementación]`
- `[el lenguaje de programción := Angler]`, en cada capítulo decir que es el lenguaje desarrollándose.
